---
name: deploy go ap

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install golang
      run: |
        sudo apt-get update
        sudo apt-get install golang
    - name: Deploy code
      run: |
        go build
        ./no-hello-bot