name: test app

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install golang
      run: |
        sudo apt-get update
        sudo apt-get install golang
    - name: Run golang tests
      run: |
        go test ./...